// Pham Minh Tan A01215507, Dec 7th 2022, Jenkins pipeline.
pipeline {
    agent any
    parameters {
        booleanParam(defaultValue: false, description: 'Run Unit Tests', name:
        'TEST')
    }
    stages{
        stage('Build') {
            steps{
                echo 'Student Number: A01215507. Group: 34'
                echo 'Installing the Python Requirements...'
                sh 'pip install -r requirements.txt'
                echo 'Requirement complete.'
            }
        }
        stage('Code Quality') {
            steps {
                script {
                    def workspace = WORKSPACE
                    echo "${env.JOB_NAME}"
                    sh "cd ..; pylint --fail-under=7 ./4850_final; cd 4850_final"
                }
            }
        }
        stage('Code Quantity') {
            steps{
                sh 'ls -l *.py | wc -l'
            }
        }
        stage('Test') {
            when {
                expression { params.TEST }
            }
            steps {
                sh 'python3 test_book_manager.py'
            }
            post {
                always {
                    junit 'test-reports/*.xml'
                }
            }
        }
        stage('Package') {
            steps {
                sh 'zip app.zip *.py'
            }
            post {
                always{
                    archiveArtifacts artifacts: 'app.zip'
                }
            }   
        }
    }
}